Vagrant.configure("2") do |config|

	config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 2
		#libvirt.storage :file, :size => '64G', :type => 'qcow2'
		libvirt.memory = '3096'
		libvirt.machine_virtual_size = 64
		#libvirt.mgmt_attach = false
		#libvirt.management_network_device = 'br0'
  end

	config.vm.provision "ansible" do |ansible|
    ansible.playbook = "/opt/playbook/playbook.yml"
  end

  config.vm.box = "peru/ubuntu-18.04-server-amd64"
  config.vm.box_version = "20190222.03"

	config.vm.network :public_network,
		:dev => "br0",
  	:mode => "bridge",
  	:type => "bridge"

	config.vm.network :public_network,
		:dev => "br-mgmt",
  	:mode => "bridge",
  	:type => "bridge"

	config.vm.network :public_network,
		:dev => "br-public",
  	:mode => "bridge",
  	:type => "bridge"

	config.vm.network :public_network,
		:dev => "br-private",
  	:mode => "bridge",
  	:type => "bridge"

	config.vm.network :public_network,
		:dev => "br-san",
  	:mode => "bridge",
  	:type => "bridge"

end
